name: bana-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - scipy
    - sklearn
    - matplotlib
    - openpyxl
    - plotly
    - keras==2.1.2
    - tensorflow==1.14
    - pystan==2.19.1.1
    - fbprophet
    - statsmodels
    - seaborn